version: '3'

services:
  base: &base
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        RAILS_ENV: production
    env_file: .env
    volumes:
      - ./storage:/app/storage
